# Generated by Django 4.1 on 2022-10-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="internalTax",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="product", name="vat", field=models.FloatField(default=21),
        ),
    ]
